version: '3.7'

services:
  app:
    image: 'winewithme-app:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql:/ec2-52-215-68-14.eu-west-1.compute.amazonaws.com/dd4nhiovvc0ni4
      - SPRING_DATASOURCE_USERNAME=jtmnvxvwslcsjg
      - SPRING_DATASOURCE_PASSWORD=compose-0215688c55e54e369313865a90535f241ff25693f44a5055ce0b28578dbac679
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123